[features]
seeds = false
[programs.devnet]
mysolanaproject = "7KtMmq5We9ktjn7ZE4Tx7fvbSCB2Jj6f8A8rbrhYQmXv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/julianalfonsoponce/.config/solana/id.json"

[scripts]
test = "node tests/mysolanaproject.js"
