[features]
seeds = false
[programs.localnet]
mysolanaproject = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/julianalfonsoponce/.config/solana/id.json"

[scripts]
test = "node tests/mysolanaproject.js"
